services:
  back:
    build: ./backend
    ports:
      - 3000:3000
    env_file:
      - database.env
      - backend.env
    volumes:
      - ./backend/src:/app/src

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  front:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
volumes:
  dbdata:
    driver: local
