GET http://localhost:3000/api/categories

###
GET http://localhost:3000/api/categories/1

###
GET http://localhost:3000/api/categories/ads

###
GET http://localhost:3000/api/categories/1/ads

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Maisons"
}

###
PUT  http://localhost:3000/api/categories/10
Content-Type: application/json

{
    "name": "Livres"
}


###
PATCH  http://localhost:3000/api/categories/27
Content-Type: application/json

{
     "title": "Goodd bike",
     "price": 9800
}

###
DELETE http://localhost:3000/api/categories/12
